// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDlOUfGRLkEc5RqQtm2_dReDfC645196j8',
    appId: '1:12350762234:web:e19a082a571ec94bb7ad43',
    messagingSenderId: '12350762234',
    projectId: 'wildlife-app-a0aa1',
    authDomain: 'wildlife-app-a0aa1.firebaseapp.com',
    storageBucket: 'wildlife-app-a0aa1.appspot.com',
    measurementId: 'G-0CEE36FXSD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAP9vSzSVBBLxqjP_XNo0jSgF_kGePRYAA',
    appId: '1:12350762234:android:e88c6cb977364df3b7ad43',
    messagingSenderId: '12350762234',
    projectId: 'wildlife-app-a0aa1',
    storageBucket: 'wildlife-app-a0aa1.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAZkgLFu7dTdp7EfBtFirwk1pvPnipwdHU',
    appId: '1:12350762234:ios:e3f71466f4cb5a3db7ad43',
    messagingSenderId: '12350762234',
    projectId: 'wildlife-app-a0aa1',
    storageBucket: 'wildlife-app-a0aa1.appspot.com',
    iosBundleId: 'com.example.wildlifeApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAZkgLFu7dTdp7EfBtFirwk1pvPnipwdHU',
    appId: '1:12350762234:ios:87e250b6315faa33b7ad43',
    messagingSenderId: '12350762234',
    projectId: 'wildlife-app-a0aa1',
    storageBucket: 'wildlife-app-a0aa1.appspot.com',
    iosBundleId: 'com.example.wildlifeApp.RunnerTests',
  );
}
